LU-5328 libcfs: fix build warnings without HAVE_LIBREADLINE
If macro HAVE_LIBREADLINE is not defined, we will hit the following
build warnings:

util/parser.c:286:13: error: ‘noop_int_fn’ defined but not used
[-Werror=unused-function]
 static void noop_int_fn(int unused) { }
util/parser.c:287:13: error: ‘noop_void_fn’ defined but not used
[-Werror=unused-function]
 static void noop_void_fn(void) { }

cc1: all warnings being treated as errors
make[4]: *** [libcfsutil_a-parser.o] Error 1
make[4]: Leaving directory `/home/wangsl/lustre-release/libcfs/libcfs'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/home/wangsl/lustre-release/libcfs/libcfs'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/wangsl/lustre-release/libcfs'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/wangsl/lustre-release'
make: *** [all] Error 2

Fix these warnings by wrapping function definition into macro.

Signed-off-by: Wang Shilong <wshilong@ddn.com>
Change-Id: Ibaff9379b9da40d2ed47c02a120142eeb4b376fd