LU-4423 lnet: backport Ebru Akagunduz from upstream
The following patches were commited to the upstream client.

--------------------------------------------------------------
Linux commit: cb03b88c28f4e4c2976b11142c1be59f284b15f3

Staging: lustre: fix return is not a function, parentheses are not required in lo.c

fix checkpatch.pl issues with return is not a function,
parentheses are not required in lo.c

Signed-off-by: Ebru Akagunduz <ebru.akagunduz@gmail.com>
Reviewed-by: Josh Triplett <josh@joshtriplett.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
--------------------------------------------------------------
Linux commit: 3f13cd9ec61c8b02c33df44a5a9103ae475d10ac
Author: Ebru Akagunduz <ebru.akagunduz@gmail.com>
Date:   Tue Oct 8 23:43:21 2013 +0300

Staging: lustre: fix space prohibited between function name and open parenthesis '(' in lo.c

Fix checkpatch.pl issues with space prohibited between
function name and open parenthesis '(' in lo.c

Signed-off-by: Ebru Akagunduz <ebru.akagunduz@gmail.com>
Reviewed-by: Josh Triplett <josh@joshtriplett.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
-------------------------------------------------------------
Linux commit: eca5b8813035d867e771a92b1eb7d917fec22f11

Staging: lustre: fix space prohibited between function name and open parenthesis '(' in module.c

Fix checkpatch.pl issues with space prohibited between
function name and open parenthesis '(' in module.c

Signed-off-by: Ebru Akagunduz <ebru.akagunduz@gmail.com>
Reviewed-by: Josh Triplett <josh@joshtriplett.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
--------------------------------------------------------------
Linux commit: eca5b8813035d867e771a92b1eb7d917fec22f11

Staging: lustre: fix space prohibited between function name and open parenthesis '(' in module.c

Fix checkpatch.pl issues with space prohibited between
function name and open parenthesis '(' in module.c

Signed-off-by: Ebru Akagunduz <ebru.akagunduz@gmail.com>
Reviewed-by: Josh Triplett <josh@joshtriplett.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
--------------------------------------------------------------
Linux commit d62403d6dd60b86e1dc9125324a1b3e78fdca913

Staging: lustre: fix ERROR: do not initialise statics to 0 or NULL in module.c

Fix checkpatch.pl issues with do not initialise statics to 0 or NULL in module.c

Signed-off-by: Ebru Akagunduz <ebru.akagunduz@gmail.com>
Reviewed-by: Josh Triplett <josh@joshtriplett.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
---------------------------------------------------------------

Signed-off-by: James Simmons <uja.ornl@yahoo.com>
Change-Id: Ieac3867e829e94975b047e9c54a7a10f971d60c6