LU-5533 ptlrpc: Update imp_msghdr_flags at CONNECTING state
Errors like

  LustreError: 13507:0:(layout.c:2042:__req_capsule_get()) @@@ Wrong
  buffer for field `dlm_rep' (1 of 1) in format `LDLM_INTENT_GETATTR':
  0 vs. 112 (server)
    req@ffff880ecfc8c000 x1476486707242176/t0(0)
    o101->soaked-MDT0000-mdc-ffff881029559c00@192.168.1.108@o2ib:12/10
    lens 576/192 e 0 to 0 dl 1408692442 ref 1 fl Complete:R/2/0 rc 0/0

turned out to be early replies being mistook as normal ones.  What
happened was:

  1. Client sent an ENQUEUE request with MSGHDR_AT_SUPPORT.

  2. Client reconnected (CONNECTING -> RECOV) because of some other
     request when Server was processing the ENQUEUE request.

  3. Client resent the request without MSGHDR_AT_SUPPORT because the
     resend happened before the imp_msghdr_flags update.  (The race is
     clearly a problem.)

  4. Client received an early reply for the initial "generation" of
     the request, mistook it to be a normal reply because of the
     absence of MSGHDR_AT_SUPPORT in the request buffer, and attempted
     to find an ldlm_reply buffer in the reply.  (Here, using request
     buffers to interpret replies is not really robust, since we reuse
     the same request buffer for resends and there is no guarantee
     against arrivals of replies for previous sending attempts.  This
     applies to both MSGHDR_AT_SUPPORT and MSGHDR_CKSUM_INCOMPAT18.)

The problem in step 4 is not easy to fix without interoperability
consequences; this patch only fixes the race in step 3.  Because all
relevant versions at this point support AT and will have
MSGHDR_CKSUM_INCOMPAT18 set, the problem described in step 4 will not
show up.

Change-Id: If3f2d0dcbd2fad14e1ab581025ef42f5c7cc43c7
Signed-off-by: Li Wei <wei.g.li@intel.com>