Revert "LU-6245 libcfs: remove cfs_fs_time handling"
This seems to be causing build failures on EL7:
cc1: all warnings being treated as errors
In file included from libcfs/include/libcfs/linux/libcfs.h:51:0,
                from libcfs/include/libcfs/libcfs.h:45,
                from lnet/include/lnet/lib-lnet.h:48,
                from lnet/lnet/api-ni.c:39:
libcfs/include/libcfs/linux/linux-time.h:111:0: error: "ktime_get_real_ts64" redefined [-Werror]
#define ktime_get_real_ts64 ktime_get_real_ts
^
In file included from include/linux/timer.h:5:0,
                from include/linux/workqueue.h:8,
                from include/linux/pm.h:25,
                from include/linux/device.h:25,
                from include/linux/node.h:17,
                from include/linux/cpu.h:17,
                from libcfs/include/libcfs/linux/linux-cpu.h:50,
                from libcfs/include/libcfs/linux/libcfs.h:50,
                from libcfs/include/libcfs/libcfs.h:45,
                from lnet/include/lnet/lib-lnet.h:48,
                from lnet/lnet/api-ni.c:39:
include/linux/ktime.h:455:0: note: this is the location of the previous definition
#define ktime_get_real_ts64(ts) getnstimeofday64(ts)
^
make[7]: *** [lnet/klnds/o2iblnd/o2iblnd.o] Error 1
make[6]: *** [lnet/klnds/o2iblnd] Error 2
make[5]: *** [lnet/klnds] Error 2
make[5]: *** Waiting for unfinished jobs....
cc1: all warnings being treated as errors
make[6]: *** [lnet/lnet/api-ni.o] Error 1
make[6]: *** Waiting for unfinished jobs....

This reverts commit c3ddfae1b795385aa14db61df1a416ab57bfc066.

Change-Id: I629bd51d27206db7c6b6251ca7089707d33287b8