LU-3137 kerberos: GSSAPI broken due to library confusion
libgssglue has replaced libgssapi on some platforms, including RHEL
6.4, producing the compile-time errors

lsvcgssd-context_lucid.o: In function `serialize_krb5_ctx':
/home/ajk/lustre-master/lustre/utils/gss/context_lucid.c:598:
undefined reference to `gss_export_lucid_sec_context'
/home/ajk/lustre-master/lustre/utils/gss/context_lucid.c:634:
undefined reference to `gss_free_lucid_sec_context'

Having Autoconf look for gss_free_lucid_sec_context() instead of
gss_init_sec_context() finds the correct library.

Signed-off-by: Andrew Korty <ajk@iu.edu>
Change-Id: I1362682a5a2cc78b176ad0b4f9181db335084cd4