LU-8163 hsm: user_request_mask can't be unset in test 24c
The following lines in sanity-hsm.sh test_24c

  set_hsm_param user_request_mask ""
  set_hsm_param group_request_mask ""
  set_hsm_param other_request_mask ""

generate the following errors in the test, which isn't caught:

  error: set_param: setting mdt.lustre-MDT0000.hsm.user_request_mask:
                    no value

This is because "lct set_param" cannot accept an empty value:

  $ lctl set_param -n mdt.lustre-MDT0000.hsm.user_request_mask=""
  error: set_param: setting mdt.lustre-MDT0000.hsm.user_request_mask:
                    no value

Since the test checked earlier that [user|group|other]_request_mask
was RESTORE, we don't actually need to change their values to
nothing. They just have to be not ARCHIVE.

Test-Parameters: trivial testlist=sanity-hsm,sanity-hsm

Signed-off-by: frank zago <fzago@cray.com>
Change-Id: I00622d93157e6577651996bf482ec8f710f86c9e