LU-1821 osc: fix build error with newer gcc
osc_setup is forgetting error when ptlrpcd_alloc_work fails.
And it causes build error.

cc1: warnings being treated as errors
osc_request.c:3581: error: ignoring return value of ‘PTR_ERR’,
declared with attribute warn_unused_result

Signed-off-by: Peng Tao <tao.peng@emc.com>
Change-Id: Ib36fefa9d33a49cfa7dbacd8e47190f467aa7d23