LU-2984 build: Fix warning with gcc-4.6+ in mdt_handler.c
gcc-4.6+ has more stricter check for possible usage of unnitialized
variables so it will generate error with -Werror like this

lustre/mdt/mdt_handler.c: In function ‘mdt_get_info’:
lustre/mdt/mdt_handler.c:5508:9: error: ‘rc’ may be used uninitialized
in this function [-Werror=maybe-uninitialized]
cc1: all warnings being treated as errors

Signed-off-by: Alexey Shvetsov <alexxy@gentoo.org>
Change-Id: Ia330808886b466c4a7d184add56b1ede115c7d0e