LDEV-17 mdt: check if the object DEAD before getattr
In mdt_getattr_name_lock(), for cross-ref object, it
gets the object before enqueue lock, so it should check
if the object being unlinked after getting the lock,
otherwise it might try to load shards of the unliked
striped dir, which will cause panic for ZFS OSD.

LustreError: 59145:0:(osd_index.c:168:osd_index_it_init()) LBUG
Pid: 59145, comm: mdt03_008
Call Trace:
[<ffffffffa04c9895>] libcfs_debug_dumpstack+0x55/0x80 [libcfs]
[<ffffffffa04c9e97>] lbug_with_loc+0x47/0xb0 [libcfs]
[<ffffffffa0e09f70>] osd_index_it_init+0x5c0/0x660 [osd_zfs]
[<ffffffffa0e0a01e>] osd_dir_it_init+0xe/0x50 [osd_zfs]
[<ffffffffa0fe72c8>] lod_load_lmv_shards+0x2b8/0xb00 [lod]
[<ffffffffa0312484>] ? nvlist_lookup_common+0x84/0xd0 [znvpair]
[<ffffffffa0312646>] ? nvlist_lookup_byte_array+0x16/0x20 [znvpair]
[<ffffffff810a4c00>] ? up+0x0/0x50
[<ffffffffa0e0575d>] ? osd_xattr_get+0x20d/0x310 [osd_zfs]
[<ffffffffa0ff0a99>] lod_xattr_get+0x509/0x760 [lod]
[<ffffffffa104e2b1>] mdd_xattr_get+0x111/0x400 [mdd]
[<ffffffffa0f068cd>] mdt_stripe_get+0xdd/0x440 [mdt]
[<ffffffffa0f06fc0>] mdt_attr_get_complex+0x390/0xc00 [mdt]
[<ffffffffa0f08004>] mdt_getattr_internal+0x2b4/0x1470 [mdt]
[<ffffffffa0f0b345>] mdt_getattr_name_lock+0x795/0x1aa0 [mdt]
[<ffffffff812945ba>] ? strlcpy+0x4a/0x60
[<ffffffffa0844514>] ? lustre_msg_get_flags+0x34/0xb0 [ptlrpc]
[<ffffffffa0845c60>] ? lustre_swab_ldlm_reply+0x0/0x40 [ptlrpc]
[<ffffffffa0f0cb72>] mdt_intent_getattr+0x292/0x470 [mdt]
[<ffffffffa0ef7cf4>] mdt_intent_policy+0x494/0xce0 [mdt]

Signed-off-by: wang di <di.wang@intel.com>
Change-Id: I1ef6bf197eac0917fd649868235c96af2f64207c